apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply from: rootProject.file('quality.gradle')

// 配置 sources jar 和 javadoc jar
java {
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    compileOnly libs.json.v20251224//提供org.json环境，开发时注意与Android org.json api兼容
    implementation project(':payload_reader')
}

sourceCompatibility = javaVersion
targetCompatibility = javaVersion

// 配置发布
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'com.gitee.maxchou'
            artifactId = 'payload_writer'
            version = '2.0.10'
        }
    }
}
