plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}
// apply from: rootProject.file('quality.gradle')

jar {
    manifest {
        attributes 'Walle-Version': VERSION_NAME
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation fileTree(dir: "./src/main/libs", include: ['*.jar'])
    implementation libs.commons.io
    implementation libs.commons.codec
    implementation libs.commons.lang3
    implementation libs.android.gradle.plugin
    implementation libs.json.v20251224
    implementation project(':payload_writer')
    implementation libs.gson
    implementation libs.guava
    implementation libs.bcpkix.jdk18on
    implementation libs.bcprov.jdk18on
}

// Configure publishing for Gradle Plugin
tasks.register('sourcesJar', Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.allSource
}

tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    archiveClassifier.set('javadoc')
    from javadoc.destinationDir
}

publishing {
    publications {
        wallePlugin(MavenPublication) {
            from components.java
            
            artifactId = 'walle-plugin'
            groupId = 'com.github.maxZhou7'
            version = '2.0.23'
            
            pom {
                name = 'Walle Gradle Plugin'
                description = 'Gradle plugin for Android APK channel packaging'
                url = 'https://github.com/maxZhou7/meituanwall'
                
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                
                developers {
                    developer {
                        id = 'maxzhou'
                        name = 'maxzhou'
                        email = 'maxzhou7@gamil.com'
                    }
                }
                
                scm {
                    connection = 'scm:git:git://github.com/maxZhou7/meituanwall.git'
                    developerConnection = 'scm:git:ssh://github.com/maxZhou7/meituanwall.git'
                    url = 'https://github.com/maxZhou7/meituanwall'
                }
            }
        }
        
        // Plugin marker artifact - required for Gradle plugin resolution
        wallePluginMarkerMaven(MavenPublication) {
            // For plugins DSL to work, the marker's coordinates must be:
            // groupId:plugin-id.gradle.plugin:version
            // Since our plugin id is 'com.github.maxZhou7.walle',
            // Gradle looks for: com.github.maxZhou7.walle:com.github.maxZhou7.walle.gradle.plugin:2.0.23
            groupId = 'com.github.maxZhou7.walle'
            artifactId = 'com.github.maxZhou7.walle.gradle.plugin'
            version = '2.0.23'
            
            // The marker artifact's POM must declare a dependency on the actual plugin implementation
            pom.withXml {
                def root = asNode()
                def dependencies = root.appendNode('dependencies')
                def dependency = dependencies.appendNode('dependency')
                dependency.appendNode('groupId', 'com.github.maxZhou7')
                dependency.appendNode('artifactId', 'walle-plugin')
                dependency.appendNode('version', '2.0.23')
            }
            
            pom {
                name = 'Walle Gradle Plugin Marker'
                description = 'Marker artifact for Walle Gradle Plugin'
                url = 'https://github.com/maxZhou7/meituanwall'
                
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                
                developers {
                    developer {
                        id = 'maxzhou'
                        name = 'maxzhou'
                        email = 'maxzhou7@gamil.com'
                    }
                }
                
                scm {
                    connection = 'scm:git:git://github.com/maxZhou7/meituanwall.git'
                    developerConnection = 'scm:git:ssh://github.com/maxZhou7/meituanwall.git'
                    url = 'https://github.com/maxZhou7/meituanwall'
                }
            }
        }
    }
}

// Configure Gradle Plugin Development
gradlePlugin {
    plugins {
        wallePlugin {
            id = 'com.github.maxZhou7.walle'
            implementationClass = 'com.meituan.android.walle.GradlePlugin'
            displayName = 'Walle Gradle Plugin'
            description = 'Gradle plugin for Android APK channel packaging'
        }
    }
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}