apply plugin: 'groovy'
apply plugin: 'maven-publish'
// apply from: rootProject.file('quality.gradle')

jar {
    manifest {
        attributes 'Walle-Version': VERSION_NAME
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation fileTree(dir: "./src/main/libs", include: ['*.jar'])
    implementation libs.commons.io
    implementation libs.commons.codec
    implementation libs.commons.lang3
    implementation libs.android.gradle.plugin
    implementation libs.json.v20251224
    implementation project(':payload_writer')
    implementation libs.gson
}

// Configure publishing
java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'com.gitee.maxchou'
            artifactId = 'walle-plugin'
            version = '2.0.9'
            
            pom {
                name = 'Walle Gradle Plugin'
                description = 'Gradle plugin for Android APK channel packaging'
                url = 'https://gitee.com/maxchou/walle'
                
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                
                developers {
                    developer {
                        id = 'maxchou'
                        name = 'maxchou'
                        email = '343095962@qq.com'
                    }
                }
                
                scm {
                    connection = 'scm:git:gitee.com/maxchou/walle.git'
                    developerConnection = 'scm:git:ssh://gitee.com/maxchou/walle.git'
                    url = 'https://gitee.com/maxchou/walle'
                }
            }
        }
    }
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}