apply plugin: 'groovy'
// apply from: rootProject.file('quality.gradle')

jar {
    manifest {
        attributes 'Walle-Version': VERSION_NAME
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation fileTree(dir: "./src/main/libs", include: ['*.jar'])
    implementation libs.commons.io
    implementation libs.commons.codec
    implementation libs.commons.lang3
    implementation libs.android.gradle.plugin
    implementation libs.json
    implementation project(':payload_writer')
    implementation libs.gson
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}