plugins {
    id 'java-library'
    alias(libs.plugins.kotlin.jvm)
}

// apply from: rootProject.file('quality.gradle')

kotlin {
    jvmToolchain(17)
}

java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

jar {
    archiveClassifier = 'all'
    manifest {
        attributes 'Main-Class': 'com.meituan.android.walle.Main'
        attributes 'Walle-Version': VERSION_NAME
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn(':payload_writer:jar', ':payload_reader:jar')
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.jcommander
    implementation libs.commons.io
    implementation project(':payload_writer')
    implementation project(':payload_reader')
    implementation libs.json.v20251224
    implementation libs.gson
}
