plugins {
    id 'java-library'
    alias(libs.plugins.shadow)
}

// apply from: rootProject.file('quality.gradle')

jar {
    manifest {
        attributes 'Main-Class': 'com.meituan.android.walle.Main'
        attributes 'Walle-Version': VERSION_NAME
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.jcommander
    implementation libs.commons.io
    implementation project(':payload_writer')
    implementation project(':payload_reader')
    implementation libs.json.v20251224
    implementation libs.gson
}

sourceCompatibility = javaVersion
targetCompatibility = javaVersion
